shop_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-src
      port: 5432
      user: postgres
      password: postgres
      dbname: mydb
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10